version: '2'
services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fund
      MYSQL_DATABASE: fund
      MYSQL_USER: fund
      MYSQL_PASSWORD: fund
      TZ: "Asia/Seoul"
    volumes:
      - ./data/db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

